### ISSUE TITLE
Exceptions in transactions are printed to stderr

### ISSUE THREAD

**Issue by taig** [typelevel/skunk#905]
Just opening a separate issue to track this. It has been bugging me for a while, but unfortunately I didn't manage to narrow it down in the skunk codebase.

> One thing that isn't quite clear from my description above, but which is included in the linked example repo, is that something inside Skunk (or a dep?) is printing exceptions that occur inside transactions directly to stderr/stdout. This doesn't happen when the exception occurs outside of an explicit transaction. We read through much Skunk code, and could not identify where this printing originates.

https://github.com/typelevel/skunk/issues/893#issuecomment-1584893801

> That's likely due to an uncaught exception in a fiber, which cats-effect then logs. If we can find the offending fiber, we could fix via .voidError or something similar.

https://github.com/typelevel/skunk/issues/893#issuecomment-1584896876

**Comment by armanbilge** [comment]
> didn't manage to narrow it down in the skunk codebase.

It could be elsewhere. For example see this one that was reported in http4s but needed to be fixed in FS2.

- https://github.com/typelevel/fs2/pull/3238

If you can make a small reproducer I can take a look.

**Comment by taig** [comment]
Requires Docker, hopefully making it more convenient for you:
https://github.com/taig/skunk-exception-printing-reproducer

**Comment by armanbilge** [comment]
Thanks, I think I found it.
- https://github.com/typelevel/skunk/pull/906
